name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Trophy SVG
        run: |
          # The -f flag prevents it from saving an error page if the server is temporarily down
          curl -f "https://github-profile-trophy.vercel.app/?username=Youssef-Amgad-Elkhatib&theme=aura&no-frame=true&margin-w=15&row=2&column=4" -o github-trophies.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-trophies.svg
          git commit -m "Update static trophies" || echo "No changes to commit"
          git push origin main
